### ISSUE TITLE
About the spatial-temporal patterns

### ISSUE THREAD

**Issue by buaaswf** [ahangchen/TFusion#4]
Hi， @ahangchen ， I read carefully your paper, it seems that the spatial-temporal features could extract the cross datasets features. However, the distribution of the time interval is specified to the cameras views.
How it solves the cross cameras and cross datasets problems?

Thank you

**Comment by ahangchen** [comment]
Spatial temporal model couldn't extract cross dataset spatial temporal features, because st features across different camera topologies are different, which is hard to use for transfer across datasets.

We use vision model trained on source dataset, and use it to extract spartial temporal feature on target dataset, without any spatial temporal infomation from source dataset.

The key to sovle this cross dataset problems is sharing of the vision model, rather than the spatial-temporal model.

**Comment by buaaswf** [comment]
ok, I understand, the spatial-temporal information is used to improve the source dataset performance, right?

**Comment by ahangchen** [comment]
No, we only care about the performance on target dataset and we don't compute spatial-temporal pattern about source dataset. The spatial-temporal information can significantly improve the performance on target dataset compared to directly transfer using vision model. That's one point, and this will provide retraining data with better quality.
